-module(space_age).

-export([ageOn/2]).

-define(EARTH_ORBITAL_PERIOD_DAYS, 365.25).
-define(EARTH_ORBITAL_PERIOD_SECONDS, 31557600).
-define(SECONDS_IN_A_EARTH_DAY, 86400).

-define(MERCURY_ORBITAL_PERIOD_EARTH_YEARS, 0.2408467).
-define(MARS_ORBITAL_PERIOD_EARTH_YEARS, 1.8808158).
-define(VENUS_ORBITAL_PERIOD_EARTH_YEARS, 0.61519726).
-define(JUPITER_ORBITAL_PERIOD_EARTH_YEARS, 11.862615).
-define(SATURN_ORBITAL_PERIOD_EARTH_YEARS, 29.447498 ).
-define(URANUS_ORBITAL_PERIOD_EARTH_YEARS,  84.016846).
-define(NEPTUNE_ORBITAL_PERIOD_EARTH_YEARS, 164.79132).


ageOn(Planet, Seconds) ->
    case Planet of 
        earth ->
            Seconds / ?EARTH_ORBITAL_PERIOD_SECONDS;
        mercury ->
            Seconds / (?EARTH_ORBITAL_PERIOD_DAYS * ?MERCURY_ORBITAL_PERIOD_EARTH_YEARS * ?SECONDS_IN_A_EARTH_DAY);
        mars ->
            Seconds / (?EARTH_ORBITAL_PERIOD_DAYS * ?MARS_ORBITAL_PERIOD_EARTH_YEARS * ?SECONDS_IN_A_EARTH_DAY);
        venus ->
            Seconds / (?EARTH_ORBITAL_PERIOD_DAYS * ?VENUS_ORBITAL_PERIOD_EARTH_YEARS * ?SECONDS_IN_A_EARTH_DAY);
        jupiter ->
            Seconds / (?EARTH_ORBITAL_PERIOD_DAYS * ?JUPITER_ORBITAL_PERIOD_EARTH_YEARS * ?SECONDS_IN_A_EARTH_DAY);
        saturn ->
            Seconds / (?EARTH_ORBITAL_PERIOD_DAYS * ?SATURN_ORBITAL_PERIOD_EARTH_YEARS * ?SECONDS_IN_A_EARTH_DAY);
        uranus ->
            Seconds / (?EARTH_ORBITAL_PERIOD_DAYS * ?URANUS_ORBITAL_PERIOD_EARTH_YEARS * ?SECONDS_IN_A_EARTH_DAY);
        neptune ->
            Seconds / (?EARTH_ORBITAL_PERIOD_DAYS * ?NEPTUNE_ORBITAL_PERIOD_EARTH_YEARS * ?SECONDS_IN_A_EARTH_DAY)
        end.    
